### ISSUE TITLE
Installer v2.0.3 install directory invalid

### ISSUE THREAD

**Issue by AndyMarshall1962** [eapowertools/qs-telemetry-dashboard#48]
I hit an error as follows after entering the install parameters.

The install directory was not valid:
Index and length must refer to a location within the string.
Parameter name : length

I am using the same folder name as was used for the old version but this time it does not like it. I replaced F: with the UNC path to the shared Qlik file store.

**Comment by rkomma4119** [comment]
I got the same error too. Attached is the debug log.
**Path:** \\QLIK09\share\TelemetryDashboard
[package.log](https://github.com/eapowertools/qs-telemetry-dashboard/files/2819083/package.log)

**Comment by levi-turner** [comment]
@rkomma4119 : Thank you for that information.

Has the previous installation been removed? Based on a run through, I am getting a failure with this scenario:

- Install 2.0.2 to `\\foo\share\TelemetryDashboard`
- Install 2.0.3 to `\\foo\share\TelemetryDashboard`:
```
Calling custom action CustomActions!CustomActions.CustomActions.ValidateInstallDir
The install directory was not valid:
Index and length must refer to a location within the string.
Parameter name: length
```
What is working is:

- Install 2.0.2 to `\\foo\share\TelemetryDashboard`
- Uninstall
- Install 2.0.3 to `\\foo\share\TelemetryDashboard`

Apologies for the confusion here but do give that a shot.

**Comment by AndyMarshall1962** [comment]
We never got 2.0.2 to install at all so there was no old installation. We tried \\server\share\telemetrydashboard\ and \\server\share\telemetrydashboard but they both failed from the msi file. Ussing msiexec from cmd(admin) mysteriously got past this but then hit the QSR connection failure again.

**Comment by rkomma4119** [comment]
> @rkomma4119 : Thank you for that information.
> 
> Has the previous installation been removed? Based on a run through, I am getting a failure with this scenario:
> 
> * Install 2.0.2 to `\\foo\share\TelemetryDashboard`
> * Install 2.0.3 to `\\foo\share\TelemetryDashboard`:
> 
> ```
> Calling custom action CustomActions!CustomActions.CustomActions.ValidateInstallDir
> The install directory was not valid:
> Index and length must refer to a location within the string.
> Parameter name: length
> ```
> What is working is:
> 
> * Install 2.0.2 to `\\foo\share\TelemetryDashboard`
> * Uninstall
> * Install 2.0.3 to `\\foo\share\TelemetryDashboard`
> 
> Apologies for the confusion here but do give that a shot.

Thanks. I uninstalled 2.0.2 and this helped. Now i was able to install 2.0.3 successfully.

**Comment by AndyMarshall1962** [comment]
We never got any version to install so the notion of uninstall is not applicable.

**Comment by jparis** [comment]
Fixed: https://github.com/eapowertools/qs-telemetry-dashboard/releases/tag/3.0.0

Will probably need to uninstall.

**Comment by fuliang2015** [comment]
I am still facing the same issue in 3.0.0 at customer environment, no previous version installed, running on Feb 2019 SR3. 
[TelemetryPacage.log](https://github.com/eapowertools/qs-telemetry-dashboard/files/3264462/TelemetryPacage.log)

**Comment by levi-turner** [comment]
@fuliang2015 : Please see Jesse's comment on this thread: https://github.com/eapowertools/qs-telemetry-dashboard/issues/67 If there are further issues comment in there.
