### ISSUE TITLE
CSV files not generated and Charts in dashboard are showing as Incomplete Visualization.

### ISSUE THREAD

**Issue by Balasupreetha** [eapowertools/qs-telemetry-dashboard#57]
Hi Qlik team,

I have corrected the paths for Telemetry metadata data connection and output dir path in the config.js folder. When I run the telemetry dashboard tasks, there are errors saying File cannot be opened. The path I used is C:\Program Files\Qlik\Sense\TelemetryMetadata. It does not have .csv files generated in it. I had used old .csv files which got generated just once(not sure how) and then the reload tasks were completing successfully.
But still, if i open the Telemetry dashboard I find many charts saying Incomplete visualization. So I have two issues here, one is csv files not getting generated and other is charts with Incomplete visualizations.

Thanks,
Supreetha

**Comment by levi-turner** [comment]
1. CSVs not generated
2. Dashboard incomplete

At a first approximation a failure of (1) can contribute to (2), so in terms of (1), please run the following command:

- Start a command prompt with admin rights
- cd "C:\Program Files\Qlik\Sense\ServiceDispatcher\Node"
  -  (or alternative install location)
- Node.exe "**\\\USRAL-LTU2\Share**\TelemetryDashboard\MetadataGenerater\fetchMetadata.js"  > C:\fetchMetadata.log 
  - (replacing the bolded portion with your share path)

And attach that log.

**Comment by drewr15** [comment]
[fetchMetadata.log](https://github.com/eapowertools/qs-telemetry-dashboard/files/2920875/fetchMetadata.log)

**Comment by Balasupreetha** [comment]
Hi Levi,

My friend from my same team(Drewr15) has uploaded the log from the environment where I am testing.

Thanks,
Supreetha

**Comment by levi-turner** [comment]
Are you stripping the slashes in the paths? Because this looks extremely odd:
```
C:Program FilesQlikSenseTelemetryMetadataapps.csv was saved.
C:Program FilesQlikSenseTelemetryMetadatasheets.csv was saved.
```

**Comment by Balasupreetha** [comment]
No. This was the output file which I had when I ran the commands shared by you.

**Comment by levi-turner** [comment]
I presume the issue has been resolved?

**Comment by Balasupreetha** [comment]
No the issues I had reported while opening this new ticket still exists.

**Comment by Balasupreetha** [comment]
I must have hit the Close issue button by mistake. Apologies. I have reopened the ticket and we are still facing the issue.

**Comment by levi-turner** [comment]
OK so a few thoughts:

1. I'd recommend against a local path. That means the launcher is apt to fail in a multi-node environment. Since there's virtually no supported Synchronized Persistence builds from Qlik, you're apt to be on Shared.
2. The `TelemetryDashboard\MetadataGenerater\config\config.js` file should look something like this:
```
var config = {
    global: {
        delimiter: '`',
        hostname: 'localhost',
        userDirectory: 'INTERNAL',
        userId: 'sa_api',
        certificatesPath: './certs/'
    },
    engine: {
        port: 4747,
        schemaPath: 'enigma.js/schemas/12.20.0.json'
    },
    repository: {
        port: 4242
    },
    filenames: {
        outputDir: "//USRAL-LTU2/Share/TelemetryDashboard/MetadataOutput/",
        outputStatus_table: "outputStatus.csv",
        apps_table: "apps.csv",
        sheets_table: "sheets.csv",
        users_table: "users.csv",
        visualizations_table: "visualizations.csv",
        metrics_table: "metrics.csv",
        customPropertyDefinitions_table: "customPropertyDefinitions.csv",
        entityCustomPropertyMap_table: "entity_customProperty.csv",
        logLevel_table: "logLevels.csv",
        systemInfo_table: "systemInfo.csv"
        // variables_table: "variables.csv",
        // masterMetrics_table: "masterMetrics.csv",
        // visualizationsMasterMetrics_table: "visualizations_masterMetrics.csv",
        // nonMasterMetrics_table: "nonMasterMetrics.csv",
    }
};

module.exports = config;
```
Note the `outputDir` path. Make sure it's using `/` and is formatted appropriately.

**Comment by Balasupreetha** [comment]
1. I am trying this Telemetry dashboard in multi-node environment and do you think that is the reason it is failing? I see one more post that metadata fetcher is still being tested for multi-node environment.

2. Yes the config.js looks exactly like this.

Should I try the install file only on single node environment?

**Comment by levi-turner** [comment]
It works in either, so single vs. multi isn't a factor of importance in my mind.

The key delta against my system (as well as another users') is that the path is being written oddly. Mine:

```
Output folder already created.
//USRAL-LTU2/Share/TelemetryDashboard/MetadataOutput/apps.csv was saved.
//USRAL-LTU2/Share/TelemetryDashboard/MetadataOutput/sheets.csv was saved.
//USRAL-LTU2/Share/TelemetryDashboard/MetadataOutput/users.csv was saved.
//USRAL-LTU2/Share/TelemetryDashboard/MetadataOutput/visualizations.csv was saved.
//USRAL-LTU2/Share/TelemetryDashboard/MetadataOutput/metrics.csv was saved.
//USRAL-LTU2/Share/TelemetryDashboard/MetadataOutput/customPropertyDefinitions.csv was saved.
//USRAL-LTU2/Share/TelemetryDashboard/MetadataOutput/entity_customProperty.csv was saved.
//USRAL-LTU2/Share/TelemetryDashboard/MetadataOutput/outputStatus.csv was saved.
//USRAL-LTU2/Share/TelemetryDashboard/MetadataOutput/logLevels.csv was saved.
//USRAL-LTU2/Share/TelemetryDashboard/MetadataOutput/systemInfo.csv was saved.
//USRAL-LTU2/Share/TelemetryDashboard/MetadataOutput/systemInfo.csv was saved.
//USRAL-LTU2/Share/TelemetryDashboard/MetadataOutput/customPropertyDefinitions.csv was saved.
//USRAL-LTU2/Share/TelemetryDashboard/MetadataOutput/users.csv was saved.
//USRAL-LTU2/Share/TelemetryDashboard/MetadataOutput/logLevels.csv was saved.
//USRAL-LTU2/Share/TelemetryDashboard/MetadataOutput/systemInfo.csv was saved.
//USRAL-LTU2/Share/TelemetryDashboard/MetadataOutput/entity_customProperty.csv was saved.
//USRAL-LTU2/Share/TelemetryDashboard/MetadataOutput/apps.csv was saved.
Getting data for app: c88f6126-ce41-4ae7-aecb-8de27c7fc218
creating a session
opening a doc.
```

What version are you running? 2.0.3?

**Comment by Balasupreetha** [comment]
The QlikSense version is Sept 2018 Patch 2 and Telemetry is the latest one downloaded from Github.

**Comment by jparis** [comment]
You need to change your outputDir in the config.js file as above. The installer now forces a network path.
